name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Backend Container
        run: |
          cd /appdata/lyricus
          docker compose up -d --build backend
          docker image prune -f